required = [
    "github.com/aws/aws-sdk-go",
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "github.com/openshift/generic-admission-server/pkg/cmd",
    "github.com/stretchr/testify/assert",
    "golang.org/x/net/context",
    "github.com/jteeuwen/go-bindata",
    "github.com/openshift/installer/pkg/types",
    "github.com/openshift/installer/pkg/destroy/azure",
    "github.com/openshift/installer/pkg/asset/installconfig/azure",
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/client-gen", # for go generate
    "k8s.io/code-generator/cmd/conversion-gen", # for go generate
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "k8s.io/code-generator/cmd/defaulter-gen", # for go generate
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
    "github.com/heptio/velero/pkg/apis/velero/v1"
]

ignored = [
    "github.com/openshift/hive/tools"
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/jteeuwen/go-bindata"
    unused-packages = false

# STANZAS BELOW ARE GENERATED AND MAY BE WRITTEN - DO NOT MODIFY BELOW THIS LINE.

[[override]]
  name="sigs.k8s.io/controller-runtime"
  branch="release-0.2"

[[override]]
  name="k8s.io/api"
  version="kubernetes-1.14.1"

[[override]]
  name="github.com/russross/blackfriday"
  version="=v1.4"

[[override]]
  name="k8s.io/kubernetes"
  version="=v1.14.1"

[[override]]
  name="k8s.io/metrics"
  version="kubernetes-1.14.1"

[[override]]
  name="k8s.io/apimachinery"
  version="kubernetes-1.14.1"

[[override]]
  name="k8s.io/kube-aggregator"
  version="kubernetes-1.14.1"

[[override]]
  name="k8s.io/cli-runtime"
  version="kubernetes-1.14.1"

[[override]]
  name="k8s.io/kube-openapi"
  revision="07b8972065522ba66df16032247530e1dbaca011"

[[override]]
  name = "k8s.io/utils"
  revision = "c55fbcfc754a5b2ec2fbae8fb9dcac36bdba6a12"

[[override]]
  name = "sigs.k8s.io/structured-merge-diff"
  revision = "e85c7b244fd2cc57bb829d73a061f93a441e63ce"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/heptio/velero"
  version = "v1.0.0"

[[override]]
  name = "k8s.io/client-go"
  version="kubernetes-1.14.1"

[[constraint]]
  name = "github.com/openshift/installer"
  revision = "344e38f31fb65dfd27184bee420e6ec0043618b7"

# Transient dep from installer, no longer detected automatically due to their switch to go modules.
[[override]]
  name = "github.com/openshift/cloud-credential-operator"
  revision = "9cc1c1abf898cfa08429d465da0f02d064bd89ee"

# Transient dep from installer, no longer detected automatically due to their switch to go modules.
[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "v38.1.0"

[[override]]
  name = "contrib.go.opencensus.io/exporter/ocagent"
  version = "v0.4.11"

[[constraint]]
  name = "github.com/openshift/generic-admission-server"
  version = "v1.14.0"
  # branch = "release-1.13" # TODO: Can't use "version" for v1.13.2 as that release is broken. Go back to using version when fixed.

[[override]]
  name = "k8s.io/apiserver"
  version="kubernetes-1.14.1"

[[override]]
  name = "github.com/evanphx/json-patch"
  version = "v4.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/openshift/api"

[[override]]
  name = "sigs.k8s.io/cluster-api-provider-aws"
  source = "github.com/openshift/cluster-api-provider-aws"
  revision = "923caeb1d0d82c42968465262387111753bda78a"

[[override]]
  name = "github.com/docker/docker"
  revision = "a9fbbdc8dd8794b20af358382ab780559bca589d"

[[override]]
  name = "github.com/jteeuwen/go-bindata"
  revision = "a0ff2567cfb70903282db057e799fd826784d41d"

[[override]]
  name="k8s.io/apiextensions-apiserver"
  version="kubernetes-1.14.1"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[[override]]
  name = "k8s.io/code-generator"
  version="kubernetes-1.14.1"

[[override]]
  name = "sigs.k8s.io/cluster-api-provider-azure"
  source = "github.com/openshift/cluster-api-provider-azure"
