apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: dnszones.hive.openshift.io
spec:
  group: hive.openshift.io
  names:
    kind: DNSZone
    plural: dnszones
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            aws:
              description: AWS specifies AWS-specific cloud configuration
              properties:
                accountSecret:
                  description: AccountSecret contains a reference to a secret that
                    contains AWS credentials for CRUD operations
                  type: object
                additionalTags:
                  description: AdditionalTags is a set of additional tags to set on
                    the DNS hosted zone. In addition to these tags,the DNS Zone controller
                    will set a hive.openhsift.io/hostedzone tag identifying the HostedZone
                    record that it belongs to.
                  items:
                    properties:
                      key:
                        description: Key is the key for the tag
                        type: string
                      value:
                        description: Value is the value for the tag
                        type: string
                    required:
                    - key
                    - value
                    type: object
                  type: array
                region:
                  description: Region specifies the region-specific API endpoint to
                    use
                  type: string
              required:
              - accountSecret
              - region
              type: object
            linkToParentDomain:
              description: LinkToParentDomain specifies whether DNS records should
                be automatically created to link this DNSZone with a parent domain.
              type: boolean
            zone:
              description: Zone is the DNS zone to host
              type: string
          required:
          - zone
          type: object
        status:
          properties:
            aws:
              description: AWSDNSZoneStatus contains status information specific to
                AWS
              properties:
                zoneID:
                  description: ZoneID is the ID of the zone in AWS
                  type: string
              type: object
            lastSyncGeneration:
              description: LastSyncGeneration is the generation of the zone resource
                that was last sync'd. This is used to know if the Object has changed
                and we should sync immediately.
              format: int64
              type: integer
            lastSyncTimestamp:
              description: LastSyncTimestamp is the time that the zone was last sync'd.
              format: date-time
              type: string
            nameServers:
              description: NameServers is a list of nameservers for this DNS zone
              items:
                type: string
              type: array
          required:
          - lastSyncGeneration
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
