---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: hiveapi-serving-cert
  labels:
    api: hiveapi
    apiserver: "true"
  name: hiveapi
  namespace: hive
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 10443
  selector:
    api: hiveapi
    apiserver: "true"
