# Adds namespace to all resources.
namespace: hive

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
#namePrefix: hive-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
#
# General rule here is anything deployed by OLM bundles should go here as well,
# this is used in "make deploy" for developers and should mimic what OLM deploys
# for you. CRDs are an exception to this as we don't want to have to list them all
# here. These are deployed via a "make install" dependency.
resources:
- ./namespace.yaml
- ./rbac/manager_role.yaml
- ./rbac/manager_role_binding.yaml
- ./rbac/hive_frontend_role.yaml
- ./rbac/hive_frontend_role_binding.yaml
- ./hiveadmission/hiveadmission_rbac_role.yaml
- ./hiveadmission/hiveadmission_rbac_role_binding.yaml
- ./operator/operator_role.yaml
- ./operator/operator_role_binding.yaml
- ./operator/operator_deployment.yaml
- ./external-dns/rbac_role.yaml
- ./external-dns/rbac_role_binding.yaml
