apiVersion: v1
kind: Template
metadata:
  name: hiveadmission-template

parameters:
- name: SERVICE_CA
  required: true
  description: Base64 encoded certificate CA used by the hiveadmission service
- name: KUBE_CA
  required: true
  description: Base64 encoded certificate CA used by the kubernetes cluster


objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: openshift-hive

# register as aggregated apiserver; this has a number of benefits:
#
# - allows other kubernetes components to talk to the the admission webhook using the `kubernetes.default.svc` service
# - allows other kubernetes components to use their in-cluster credentials to communicate with the webhook
# - allows you to test the webhook using kubectl
# - allows you to govern access to the webhook using RBAC
# - prevents other extension API servers from leaking their service account tokens to the webhook
#
# for more information, see: https://kubernetes.io/blog/2018/01/extensible-admission-is-beta
- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1alpha1.admission.hive.openshift.io
  spec:
    caBundle: ${SERVICE_CA}
    group: admission.hive.openshift.io
    groupPriorityMinimum: 1000
    versionPriority: 15
    service:
      name: hiveadmission
      namespace: openshift-hive
    version: v1alpha1

# register to intercept DNSZone object creates and updates
- apiVersion: admissionregistration.k8s.io/v1beta1
  kind: ValidatingWebhookConfiguration
  metadata:
    name: dnszones.admission.hive.openshift.io
  webhooks:
  - name: dnszones.admission.hive.openshift.io
    clientConfig:
      service:
        # reach the webhook via the registered aggregated API
        namespace: default
        name: kubernetes
        path: /apis/admission.hive.openshift.io/v1alpha1/dnszones
      caBundle: ${KUBE_CA}
    rules:
    - operations:
      - CREATE
      - UPDATE
      apiGroups:
      - hive.openshift.io
      apiVersions:
      - v1alpha1
      resources:
      - dnszones
    failurePolicy: Fail

# register to intercept ClusterDeployment object creates and updates
- apiVersion: admissionregistration.k8s.io/v1beta1
  kind: ValidatingWebhookConfiguration
  metadata:
    name: clusterdeployments.admission.hive.openshift.io
  webhooks:
  - name: clusterdeployments.admission.hive.openshift.io
    clientConfig:
      service:
        # reach the webhook via the registered aggregated API
        namespace: default
        name: kubernetes
        path: /apis/admission.hive.openshift.io/v1alpha1/clusterdeployments
      caBundle: ${KUBE_CA}
    rules:
    - operations:
      - CREATE
      - UPDATE
      apiGroups:
      - hive.openshift.io
      apiVersions:
      - v1alpha1
      resources:
      - clusterdeployments
    failurePolicy: Fail